### ISSUE TITLE
Build process failing on CSS files

### ISSUE THREAD

**Issue by NicholasLYang** [rob2d/generator-react-redux-gulp#2]
CSS files don't seem to be exporting properly. The files are named `materialdesignicons.css.map` and `materialdesignicons.min.css.map`. First, why have the minified file and not use it? Second, why the map at the end? Also the file `main-index.css` never builds

**Comment by rob2d** [comment]
Thanks for the report. 

Will look into the issue of not also .css along with the maps and man-index.css. 

Also, that is a good point; Nice catch. Since the .map files are there, we should be using .min by default.

**Comment by rob2d** [comment]
On second thought; since our build process minified things by default (see the gulp `html-ref-and-concat-css` process), it would make more sense to simply not include minified files since it's less optimal for debugging.

As a more holistic solution, I renamed the `dist` distribution sub folders to `dist/dev` and `dist/prod` instead of `dist/src` and `dist/build`, so it's more obvious what the purpose of the structure is. Will be pushing an update out soon.
