### ISSUE TITLE
Built CSS files become type text/html when requested in deep paths 

### ISSUE THREAD

**Issue by squirrelsquirrel78** [rob2d/generator-react-redux-gulp#8]
To preface this writeup, I define a deep path as a path with two or more "sections":
```
/news/campaign-coverage                                   <-- a deep path
/opinion/staff-editorials/the-markers-of-an-office        <-- a deep path
/news                                                     <-- not a deep path
```
Whenever I directly request a URL that is a deep path, my styles get messed up because the text of all the CSS files are replaced with the exact text from `index.html`.  

To reproduce this exception:
```
git clone git@github.com:stuyspec/client-app.git
git checkout feature/accounts
npm install
gulp dev
```
In a separate terminal and the same directory, run 
```
node app --dev
```
In a separate terminal, use httpie to see the results of the following two paths.
```
http localhost:3002/css/main-index.css
http localhost:3002/news/main-index.css
```
As the second command reveals, the built css files for a deep path is actually HTML.

P.S. No idea if this helps, but I am also receiving this error whenever I access a deep path:  
`WebSocket connection to 'ws://localhost:4474/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED` at `VM<number>:161`. I am also receiving this warning whenever I access a deep path: `DevTools failed to parse SourceMap: http://localhost:3002/css/bootstrap.min.css.map`.

**Comment by rob2d** [comment]
Thanks for the report; I'll check that out.

**Comment by rob2d** [comment]
There seems to be an issue with security/SSH keys on your repo; could not clone.

**Comment by rob2d** [comment]
the command git checkout feature/accounts does not work on my machine; ssh/etc not setup so I use source tree. Is there an alternate way to install?

**Comment by squirrelsquirrel78** [comment]
I've given you an [invitation](https://github.com/stuyspec/client-app/invitations) to READ access to the repository.

**Comment by rob2d** [comment]
this problem is due to user error. There's no file at `/news/main-index.css`. On your server side hosting app, you are routing all paths as a fallback to `index.html`, which is what is loading. I've recommended before explicitly not to do this -- one important reason is not being able to catch URLs that don't match any resources while developing.

**Comment by rob2d** [comment]
Although this is out of scope of this repo, to link to a static resource, preface it in your code by including the `href`/`src` as `"/resource"` for the URL rather than `"resource"`. Since your CSS files sit in `"/css"`, you always reference those as `"/css/**/whatever.css"`; there's isn't really a practical reason to relative directories for `"/news"` (and if you did, you would need to handle that on the express server).

https://css-tricks.com/quick-reminder-about-file-paths/

**Comment by squirrelsquirrel78** [comment]
Thank you so much! Changing my file paths fixed my css problem.
